fix exitCode for disabled tests

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -47,13 +47,22 @@ jobs:
           echo "E2E_EXIT_CODE=$exit_code" >> $GITHUB_OUTPUT
           echo "### Test logs ###"
           docker logs rococo-e-2-e
-          if [ "$exit_code" -eq "0" ]; then
+          if docker logs rococo-e-2-e | grep -q "BUILD SUCCESSFUL"; then
+            echo "E2E_EXIT_CODE=0" >> $GITHUB_OUTPUT
             echo "Tests passed successfully!"
             exit 0
           else
+            echo "E2E_EXIT_CODE=1" >> $GITHUB_OUTPUT
             echo "Tests failed!"
             exit 1
           fi
+#          if [ "$exit_code" -eq "0" ]; then
+#            echo "Tests passed successfully!"
+#            exit 0
+#          else
+#            echo "Tests failed!"
+#            exit 1
+#          fi
       - name: Add comment to PR with link to allure
         if: always()
         uses: actions/github-script@v7
